version: "3"

services:
  memospark:
    container_name: memospark
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
