import './globals.css';
import { GlobalCommand } from './ui/global-command';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Memospark',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <SessionProvider basePath="/auth">
          <main>{children}</main>
          <Toaster richColors />
          <GlobalCommand />
        </SessionProvider>
      </body>
    </html>
  );
}
